# Generated by Django 2.1.3 on 2018-11-05 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ('-modifyDate',), 'verbose_name': 'info', 'verbose_name_plural': 'infos'},
        ),
    ]
